_commit: v1.6.0
_src_path: gh:superlinear-ai/substrate
author_email: maugx3@gmail.com
author_name: Mauricio Gioachini
project_description: Analyses an user's starred repos and provides recommendations
    for your current project.
project_name: Starred Repo Analysis
project_type: package
project_url: https://github.com/MauGx3/starred-repo-analysis
python_version: '3.10'
typing: strict
with_conventional_commits: true
with_typer_cli: false
