site_name: Starred Repo Analysis
site_description: Analyses an user's starred repos and provides recommendations for your current project.
site_url: https://MauGx3.github.io/starred-repo-analysis
repo_url: https://github.com/MauGx3/starred-repo-analysis
repo_name: MauGx3/starred-repo-analysis

strict: true

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

theme:
  name: material

nav:
  - Home: index.md
  - Reference: reference.md

watch:
  - src

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
