name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Install ML/runtime extras required by some modules and tests (numpy, scikit-learn, sentence-transformers).
          # Keep this non-fatal to avoid blocking on optional ML package installation failures.
          pip install -r requirements-ml.txt || true
          pip install -r requirements-dev.txt || true

      - name: Lint (ruff)
        continue-on-error: true
        run: |
          ruff check src tests

      - name: Run tests
        run: |
          PYTHONPATH=src pytest -q

  ml:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.11
      - name: Install ML deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ml.txt
          pip install -r requirements-dev.txt || true
      - name: Run ML smoke tests
        run: |
          PYTHONPATH=src pytest -q -k smoke || true
