name: Documentation

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt || true

      - name: Build docs
        run: |
          python -m mkdocs build
      
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
        
      - name: Upload GitHub Pages artifact 
        uses: actions/upload-pages-artifact@v4
        with:
          path: site
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4