name: PR

on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

jobs:
  title:
    runs-on: ubuntu-latest

    name: Check PR title

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install commitizen
        run: |
          python -m pip install --upgrade pip
          pip install commitizen

      - name: Check PR title
        run: |
          cz check --message "${{ github.event.pull_request.title }}"
