name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Ensure PyPI token present
        if: ${{ secrets.PYPI_API_TOKEN == '' }}
        run: |
          echo "PYPI_API_TOKEN is not set; failing publish job to avoid accidental publish"
          exit 1

      - name: Publish package
        if: ${{ secrets.PYPI_API_TOKEN != '' }}
        run: |
          uv build
          uv publish
